#!/bin/sh
#
FC=     ifort
FOPTS= 
CMD=    ecm_gfs_look_alike
                                                                                                
SRCS=  ecm_gfs_look_alike.f90 \
	/nwprod/lib/libbufr_4_64.a \
	/nwprod/lib/libip_4.a \
	/nwprod/lib/libsp_4.a \
	/nwprod/lib/libbacio_4.a \
	/nwprod/lib/libw3emc_4.a \
	/nwprod/lib/libw3nco_4.a
$(CMD): $(SRCS)
	$(FC) $(FOPTS) $(SRCS) $(LIBS) -o $(CMD)

